name: Crowdin Action

on:
  push:
    branches: [main]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Crowdin action
        uses: crowdin/github-action@v1.20.2
        with:
          export_only_approved: true
          download_translations: true
          skip_untranslated_files: true
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
